// GENERATED by scripts/build-partner-logos.mjs — do not edit by hand.
//
// width and height are the display size in CSS pixels; the image files are
// written at 2x that for high-density screens.

export type PartnerGroup = 'group' | 'network'

export type PartnerLogo = {
  readonly slug: string
  readonly name: string
  readonly group: PartnerGroup
  readonly src: string
  readonly width: number
  readonly height: number
}

export const PARTNER_LOGOS: readonly PartnerLogo[] = [
  {
    slug: 'mabani-al-jazeera',
    name: 'Mabani Al Jazeera',
    group: 'group',
    src: '/partners/mabani-al-jazeera.webp',
    width: 88,
    height: 76,
  },
  {
    slug: 'takween',
    name: 'Takween Metal Industries',
    group: 'group',
    src: '/partners/takween.webp',
    width: 115,
    height: 67,
  },
  {
    slug: 'mabani-projects',
    name: 'Mabani for Projects',
    group: 'group',
    src: '/partners/mabani-projects.webp',
    width: 103,
    height: 74,
  },
  {
    slug: 'swan-properties',
    name: 'Swan Properties',
    group: 'group',
    src: '/partners/swan-properties.webp',
    width: 53,
    height: 76,
  },
  {
    slug: 'sabic',
    name: 'SABIC',
    group: 'network',
    src: '/partners/sabic.webp',
    width: 123,
    height: 63,
  },
  {
    slug: 'yanbu-cement',
    name: 'Yanbu Cement',
    group: 'network',
    src: '/partners/yanbu-cement.webp',
    width: 76,
    height: 76,
  },
  {
    slug: 'alfanar',
    name: 'alfanar',
    group: 'network',
    src: '/partners/alfanar.webp',
    width: 164,
    height: 47,
  },
  {
    slug: 'jotun',
    name: 'Jotun',
    group: 'network',
    src: '/partners/jotun.webp',
    width: 160,
    height: 48,
  },
  {
    slug: 'tameer-steel',
    name: 'Tameer Steel',
    group: 'network',
    src: '/partners/tameer-steel.webp',
    width: 135,
    height: 57,
  },
  {
    slug: 'elsewedy',
    name: 'Elsewedy Industries',
    group: 'network',
    src: '/partners/elsewedy.webp',
    width: 105,
    height: 73,
  },
  {
    slug: 'naffco',
    name: 'NAFFCO',
    group: 'network',
    src: '/partners/naffco.webp',
    width: 136,
    height: 56,
  },
  {
    slug: 'al-ittefaq-steel',
    name: 'Al-Ittefaq Steel',
    group: 'network',
    src: '/partners/al-ittefaq-steel.webp',
    width: 64,
    height: 76,
  },
  {
    slug: 'bahra-electric',
    name: 'BAHRA Electric',
    group: 'network',
    src: '/partners/bahra-electric.webp',
    width: 187,
    height: 41,
  },
  {
    slug: 'manarco',
    name: 'MANARCO',
    group: 'network',
    src: '/partners/manarco.webp',
    width: 84,
    height: 76,
  },
]
